// Print-bundle downloads: zips of every STL for a module variant's
// recommended build (print-ready orientation), generated by
// scripts/build_bundles.py and published as GitHub Release assets.
// Assets are re-uploaded in place when parts change; the tag is stable.
const RELEASE_BASE =
  "https://github.com/gearfinity/gearfinity/releases/download/bundles-v1";

export function bundleUrl(moduleId: string, variant: string): string {
  return `${RELEASE_BASE}/${moduleId}_${variant}_print.zip`;
}

export function youtubeId(url?: string): string | null {
  if (!url) return null;
  const m = url.match(/(?:v=|youtu\.be\/)([\w-]{6,})/);
  return m ? m[1] : null;
}
